// automatically generated by the FlatBuffers compiler, do not modify

package ee.cyber.cdoc20.fbs.header;

@SuppressWarnings("unused")
public final class Capsule {
  private Capsule() { }
  public static final byte NONE = 0;
  public static final byte recipients_ECCPublicKeyCapsule = 1;
  public static final byte recipients_RSAPublicKeyCapsule = 2;
  public static final byte recipients_KeyServerCapsule = 3;
  public static final byte recipients_SymmetricKeyCapsule = 4;

  public static final String[] names = { "NONE", "recipients_ECCPublicKeyCapsule", "recipients_RSAPublicKeyCapsule", "recipients_KeyServerCapsule", "recipients_SymmetricKeyCapsule", };

  public static String name(int e) { return names[e]; }
}

