// automatically generated by the FlatBuffers compiler, do not modify

package ee.cyber.cdoc20.fbs.header;

@SuppressWarnings("unused")
public final class FMKEncryptionMethod {
  private FMKEncryptionMethod() { }
  public static final byte UNKNOWN = 0;
  public static final byte XOR = 1;

  public static final String[] names = { "UNKNOWN", "XOR", };

  public static String name(int e) { return names[e]; }
}

