// automatically generated by the FlatBuffers compiler, do not modify

package ee.cyber.cdoc20.fbs.header;

@SuppressWarnings("unused")
public final class PayloadEncryptionMethod {
  private PayloadEncryptionMethod() { }
  public static final byte UNKNOWN = 0;
  public static final byte CHACHA20POLY1305 = 1;

  public static final String[] names = { "UNKNOWN", "CHACHA20POLY1305", };

  public static String name(int e) { return names[e]; }
}

