// automatically generated by the FlatBuffers compiler, do not modify

package ee.cyber.cdoc20.fbs.recipients;

public final class EllipticCurve {
  private EllipticCurve() { }
  public static final byte UNKNOWN = 0;
  public static final byte secp384r1 = 1;

  public static final String[] names = { "UNKNOWN", "secp384r1", };

  public static String name(int e) { return names[e]; }
}

