// automatically generated by the FlatBuffers compiler, do not modify

package ee.cyber.cdoc20.fbs.recipients;

@SuppressWarnings("unused")
public final class KeyDetailsUnion {
  private KeyDetailsUnion() { }
  public static final byte NONE = 0;
  public static final byte EccKeyDetails = 1;
  public static final byte RsaKeyDetails = 2;

  public static final String[] names = { "NONE", "EccKeyDetails", "RsaKeyDetails", };

  public static String name(int e) { return names[e]; }
}

