// automatically generated by the FlatBuffers compiler, do not modify

package ee.cyber.cdoc20.fbs.recipients;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.Table;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class RSAPublicKeyCapsule extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_2_0_8(); }
  public static RSAPublicKeyCapsule getRootAsRSAPublicKeyCapsule(ByteBuffer _bb) { return getRootAsRSAPublicKeyCapsule(_bb, new RSAPublicKeyCapsule()); }
  public static RSAPublicKeyCapsule getRootAsRSAPublicKeyCapsule(ByteBuffer _bb, RSAPublicKeyCapsule obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public RSAPublicKeyCapsule __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int recipientPublicKey(int j) { int o = __offset(4); return o != 0 ? bb.get(__vector(o) + j * 1) & 0xFF : 0; }
  public int recipientPublicKeyLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public ByteVector recipientPublicKeyVector() { return recipientPublicKeyVector(new ByteVector()); }
  public ByteVector recipientPublicKeyVector(ByteVector obj) { int o = __offset(4); return o != 0 ? obj.__assign(__vector(o), bb) : null; }
  public ByteBuffer recipientPublicKeyAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer recipientPublicKeyInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public int encryptedKek(int j) { int o = __offset(6); return o != 0 ? bb.get(__vector(o) + j * 1) & 0xFF : 0; }
  public int encryptedKekLength() { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; }
  public ByteVector encryptedKekVector() { return encryptedKekVector(new ByteVector()); }
  public ByteVector encryptedKekVector(ByteVector obj) { int o = __offset(6); return o != 0 ? obj.__assign(__vector(o), bb) : null; }
  public ByteBuffer encryptedKekAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer encryptedKekInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }

  public static int createRSAPublicKeyCapsule(FlatBufferBuilder builder,
      int recipientPublicKeyOffset,
      int encryptedKekOffset) {
    builder.startTable(2);
    RSAPublicKeyCapsule.addEncryptedKek(builder, encryptedKekOffset);
    RSAPublicKeyCapsule.addRecipientPublicKey(builder, recipientPublicKeyOffset);
    return RSAPublicKeyCapsule.endRSAPublicKeyCapsule(builder);
  }

  public static void startRSAPublicKeyCapsule(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addRecipientPublicKey(FlatBufferBuilder builder, int recipientPublicKeyOffset) { builder.addOffset(0, recipientPublicKeyOffset, 0); }
  public static int createRecipientPublicKeyVector(FlatBufferBuilder builder, byte[] data) { return builder.createByteVector(data); }
  public static int createRecipientPublicKeyVector(FlatBufferBuilder builder, ByteBuffer data) { return builder.createByteVector(data); }
  public static void startRecipientPublicKeyVector(FlatBufferBuilder builder, int numElems) { builder.startVector(1, numElems, 1); }
  public static void addEncryptedKek(FlatBufferBuilder builder, int encryptedKekOffset) { builder.addOffset(1, encryptedKekOffset, 0); }
  public static int createEncryptedKekVector(FlatBufferBuilder builder, byte[] data) { return builder.createByteVector(data); }
  public static int createEncryptedKekVector(FlatBufferBuilder builder, ByteBuffer data) { return builder.createByteVector(data); }
  public static void startEncryptedKekVector(FlatBufferBuilder builder, int numElems) { builder.startVector(1, numElems, 1); }
  public static int endRSAPublicKeyCapsule(FlatBufferBuilder builder) {
    int o = builder.endTable();
    builder.required(o, 4);  // recipient_public_key
    builder.required(o, 6);  // encrypted_kek
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public RSAPublicKeyCapsule get(int j) { return get(new RSAPublicKeyCapsule(), j); }
    public RSAPublicKeyCapsule get(RSAPublicKeyCapsule obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

