# TODO: Remove ports from here, once server is updated
key-shares.servers.urls=https://cdoc2-shares.dev.riaint.ee:443, https://cdoc2-sharesexternal.dev.riaint.ee:443
key-shares.servers.min_num=2
key-shares.algorithm=n-of-n

# trusted certificates by client
cdoc2.key-shares.client.ssl.trust-store=config/ria-dev/clienttruststore_ria-dev.jks
cdoc2.key-shares.client.ssl.trust-store.type=JKS
cdoc2.key-shares.client.ssl.trust-store-password=passwd

cdoc2.client.server.debug=true