rp-server.client.hostUrl=https://cdoc2-rp.dev.riaint.ee
rp-server.client.certificateLevel=QUALIFIED

rp-server.client.ssl.trust-store=config/ria-dev/clienttruststore_ria-dev.jks
rp-server.client.ssl.trust-store-password=passwd

rp-server.sid.signing-certificate.trust-store=classpath:smart-id/smartid_demo_server_trusted_ssl_certs.jks
rp-server.sid.signing-certificate.trust-store-password=passwd
rp-server.mid.signing-certificate.trust-store=classpath:mobile-id/mobileid_demo_server_trusted_ssl_certs.p12
rp-server.mid.signing-certificate.trust-store-password=passwd

cdoc2.client.server.debug=true