rp-server.client.hostUrl=https://cdoc2-rp.dev.riaint.ee
rp-server.client.certificateLevel=QUALIFIED

rp-server.client.ssl.trust-store=config/ria-dev/clienttruststore_ria-dev.jks
rp-server.client.ssl.trust-store-password=passwd

rp-server.client.read-timeout=5000
rp-server.client.connect-timeout=5000
rp-server.client.polling.intervalMs=1000
rp-server.client.polling.maxCount=0

cdoc2.client.server.debug=true
